### ISSUE TITLE
New rule on Amazon EC2 instance to check Public IP association.

### ISSUE THREAD

**Issue by shikharj05** [awslabs/aws-config-rules#159]
New rule on Amazon EC2 instance to check Public IP association (EC2_INSTANCE_NO_PUBLIC_IPv4_IP).
Please provide comments on the gherkin if any.

---

**Description:**
  Checks whether Amazon EC2 instances have a public IP association or not. The rule is NON_COMPLIANT if the publicIp field is present in the Amazon EC2 instance configuration item.
**Trigger:**
  Configuration Change on AWS::EC2::Instance
**Reports on:**
  AWS::EC2::Instance
**Rule Parameters:**
  None

```
Scenarios:
  Scenario: 1
     Given: The publicIp field is present in the Amazon EC2 instance configuration item.
     Then: Return NON_COMPLIANT
  Scenario: 2
     Given: The publicIp field is not present in the Amazon EC2 instance configuration item.
     Then: Return COMPLIANT
```
