### ISSUE TITLE
New rule on Amazon Elasticsearch Service (Amazon ES) domains to check if node to node encryption is enabled.

### ISSUE THREAD

**Issue by shikharj05** [awslabs/aws-config-rules#160]
New rule on Amazon Elasticsearch Service (Amazon ES) domains to check if node to node encryption is enabled (ELASTICSEARCH_NODE_TO_NODE_ENCRYPTION_CHECK).
Please provide comments on the gherkin if any.

---

**Description:**
  Checks whether Amazon Elasticsearch Service (Amazon ES) domains have node to node encryption configuration enabled. The rule is NON_COMPLIANT if node to node encryption is not enabled.
**Trigger:**
  Periodic
**Reports on:**
  AWS::Elasticsearch::Domain
**Rule Parameters:**
  None
```
Scenarios:
  Scenario: 1
     Given: No Amazon Elasticsearch Service (Amazon ES) domains are present in a region for an account.
     Then: Return NOT_APPLICABLE
  Scenario: 2
     Given: NodeToNodeEncryptionOptions field is Enabled:true
     Then: Return COMPLIANT
  Scenario: 3
     Given: NodeToNodeEncryptionOptions field is Enabled:false
     Then: Return NON_COMPLIANT
```
