### ISSUE TITLE
New rule on Amazon Elasticsearch Service domains to check if encryption at rest is enabled

### ISSUE THREAD

**Issue by kritijha** [awslabs/aws-config-rules#161]
New rule on Amazon Elasticsearch Service (Amazon ES) domains to check if encryption at rest is enabled (ELASTICSEARCH_ENCRYPTED_AT_REST).
Please provide comments on the gherkin if any.

---
Description:
  Checks whether Amazon Elasticsearch Service (Amazon ES) domains have encryption at rest configuration enabled. The resource is NON_COMPLIANT if encryption at rest is not enabled.
Trigger:
  Periodic
Reports on:
  AWS::Elasticsearch::Domain
Rule Parameters:
  None
```
Scenarios:
  Scenario: 1
     Given: No Amazon Elasticsearch Service (Amazon ES) domains are present in a region for an account.
     Then: Return NOT_APPLICABLE
  Scenario: 2
     Given: At least one Elasticsearch Service Domain is present
     Given: Enabled field is true in EncryptionAtRestOptions
     Then: Return COMPLIANT
  Scenario: 3
     Given: At least one Elasticsearch Service Domain is present
     Given: Enabled field is false in EncryptionAtRestOptions
     Then: Return NON_COMPLIANT
```
