### ISSUE TITLE
New rule on AWS Lambda to check Lambda is in a VPC or not

### ISSUE THREAD

**Issue by Devashish007** [awslabs/aws-config-rules#162]
New rule on AWS Lambda to check if the Lambda function is in a VPC (LAMBDA_VPC_CHECK).
Please provide comments on the gherkin if any.

```
Description:
Checks whether the AWS Lambda function is in a VPC or not. The rule is NON_COMPLIANT if the Lambda function is not in a VPC.
Trigger:
Configuration Change
Reports on:
AWS::Lambda::Function
Rule Parameters:
  subnetId
  (Optional) Comma-separated list of Subnet ID's that Lambda fuctions must belong to.

Scenarios:
  Scenario: 1
     Given: No Lambda functions are present
     Then: Return NOT_APPLICABLE
  Scenario: 2
     Given: Lambda function is present in the VPC i.e. VPC enabled:true
     And: Rule Parameter subnetId is empty
     Then: Return COMPLIANT
  Scenario: 3
     Given: Lambda function is not present in the VPC i.e. VPC enabled:false
     Then: Return NON_COMPLIANT
  Scenario: 4
      Given: Lambda function is present in the VPC i.e. VPC enabled:true
      And: Rule Parameter list doesn't match with the subnetId
      Then: Return NON_COMPLIANT
  Scenario: 5
      Given: Lambda function is present in the VPC i.e. VPC enabled:true
      And: Rule Parameter list matches with the subnetId
      Then: Return COMPLIANT

```

**Comment by jongogogo** [comment]
@dboyd13

**Comment by jongogogo** [comment]
Some comments:
1. No whitelisting. We have instructions to not include it in the rule directly.
2. Add a parameter on a comma separated vpcId to check if the lambda is in the correct VPC.
3. Why `periodic` and not `Configuration Change` ?
4. Document the API you will call if any.

**Comment by Devashish007** [comment]
1. Okay will remove whitelisting
2. Made the changes as below
3. Sorry my bad, It should have been Configuration trigger change 
4. API call: https://docs.aws.amazon.com/cli/latest/reference/lambda/get-function.html

Updated Gherkin:

```
Description:
Checks whether the AWS Lambda function is in a VPC or not. The rule is NON_COMPLIANT if the Lambda function is not in a VPC.
Trigger:
Configuration Change
Reports on:
AWS::Lambda::Function
Rule Parameters:
Comma Seperated List of VPC ID's to check if Lambda belongs to that VPC

Scenarios:
  Scenario: 1
     Given: No Lambda functions are present in a region for an account.
     Then: Return NOT_APPLICABLE
  Scenario: 2
     Given: Lambda function is present in the VPC i.e. VPC enabled:true
     And: Rule Parameter list is empty
     Then: Return COMPLIANT
  Scenario: 3
     Given: Lambda function is not present in the VPC i.e. VPC enabled:false
     Then: Return NON_COMPLIANT
  Scenario: 4
      Given: Lambda function is present in the VPC i.e. VPC enabled:true
      And: Rule Paramater list doesn't match with the VPC ID
      Then: Return NON_COMPLIANT
  Scenario: 5
      Given: Lambda function is present in the VPC i.e. VPC enabled:true
      And: Rule Paramater list matches with the VPC ID
      Then: Return COMPLIANT
```
