### ISSUE TITLE
New rule on AWS Lambda to check if function-level concurrent execution limit is set

### ISSUE THREAD

**Issue by Devashish007** [awslabs/aws-config-rules#167]
New rule on AWS Lambda to check if function-level concurrent execution limit is set (LAMBDA_CONCURRENCY_CHECK).

Please provide comments on the gherkin if any.

```
Description:
  Checks whether the AWS Lambda function is configured for function-level concurrent execution limit. The rule is NON_COMPLIANT if the Lambda function is not configured for function-level concurrent execution limit.

Trigger:
  Periodic

Reports on:
  AWS::Lambda::Function

Rule Parameters:
  concurrencyLimitLow (Optional) 
    The lower limit for the function concurrency

  concurrencyLimitHigh (Optional)
    The higher limit for the function concurrency

Scenarios:
  Scenario: 1
    Given: concurrencyLimitLow is configured
      And: concurrencyLimitLow is not an positive integer
     Then: Return an Error
  Scenario: 2
    Given: No Lambda functions are present
     Then: Return NOT_APPLICABLE
  Scenario: 3
    Given: At least 1 Lambda function is present
      And: Lambda function is not configured for Concurrency i.e. Concurrency is not set
     Then: Return NON_COMPLIANT
  Scenario: 4
    Given: At least 1 Lambda function is present
      And: Lambda function is configured for Concurrency i.e. Concurrency is set
      And: the concurrencyLimitLow parameter is not configured
      And: the concurrencyLimitHigh parameter is not configured
     Then: Return COMPLIANT
  Scenario: 5
    Given: At least 1 Lambda function is present
      And: Lambda function is configured for Concurrency i.e. Concurrency is set
      And: the concurrencyLimitLow parameter is configured and valid
      And: the function concurrency < concurrencyLimitLow
     Then: Return NON_COMPLIANT
  Scenario: 6
    Given: At least 1 Lambda function is present
      And: Lambda function is configured for Concurrency i.e. Concurrency is set
      And: the concurrencyLimitLow parameter is configured and valid
      And: the function concurrency ≥ concurrencyLimitLow
      And: the concurrencyLimitHigh parameter is not configured
     Then: Return COMPLIANT
  Scenario: 7
    Given: At least 1 Lambda function is present
      And: Lambda function is configured for Concurrency i.e. Concurrency is set
      And: the concurrencyLimitHigh parameter is configured and valid
      And: the function concurrency > concurrencyLimitHigh
     Then: Return NON_COMPLIANT
  Scenario: 8
    Given: At least 1 Lambda function is present
      And: Lambda function is configured for Concurrency i.e. Concurrency is set
      And: the concurrencyLimitHigh parameter is configured and valid
      And: the function concurrency ≤ concurrencyLimitHigh
      And: the concurrencyLimitLow parameter is not configured
     Then: Return COMPLIANT
  Scenario: 9
    Given: At least 1 Lambda function is present
      And: Lambda function is configured for Concurrency i.e. Concurrency is set
      And: the concurrencyLimitLow parameter is configured and valid
      And: the function concurrency ≥ concurrencyLimitLow
      And: the concurrencyLimitHigh parameter is configured and valid
      And: the function concurrency ≤ concurrencyLimitHigh
     Then: Return COMPLIANT
```
