### ISSUE TITLE
Configuration change rule for API_GW_NOT_EDGE_OPTIMISED

### ISSUE THREAD

**Issue by shikharj05** [awslabs/aws-config-rules#179]
Rule on Amazon API Gateway to check that APIs are not edge optimised (API_GW_NOT_EDGE_OPTIMISED).
Please provide comments on the gherkin if any.

---
**Description:**
  Checks that Amazon API Gateway APIs are not edge optimised. The rule returns NON_COMPLIANT if the RestApi's endpointConfiguration is of type EDGE.
**Trigger:**
  Configuration Change on AWS::ApiGateway::RestApi
**Reports on:**
  AWS::ApiGateway::RestApi
**Rule Parameters:**
  None
```
Scenarios:
  Scenario: 1
     Given: The endpointConfiguration type is EDGE in the RestApi configuration item.
     Then: Return NON_COMPLIANT
  Scenario: 2
     Given: The endpointConfiguration type is not EDGE in the RestApi configuration item.
     Then: Return COMPLIANT
```
