### ISSUE TITLE
New rule on Amazon API Gateway API_GW_ENPOINT_TYPE_CHECK

### ISSUE THREAD

**Issue by shikharj05** [awslabs/aws-config-rules#180]
Checks that Amazon API Gateway APIs are of type as specified in the rule parameter 'endpointConfiguration Type'. Please provide comments on the gherkin if any.

```
Description:
  Checks that Amazon API Gateway APIs are of type as specified in the rule parameter 'endpointConfiguration Type'. The rule returns NON_COMPLIANT if the RestApi does not match the endpoint type configured in the rule parameter.

Trigger:
  Configuration Change on AWS::ApiGateway::RestApi

Reports on:
  AWS::ApiGateway::RestApi

Rule Parameters:
  endpointConfiguration Type
  (Required) Comma-separated list of allowed endpoint types.

Scenarios:
  Scenario: 1
    Given: The rule parameter is not provided
     Then: Return ERROR
  Scenario: 2
    Given: The rule parameter is invalid
     Then: Return ERROR     
  Scenario: 3
    Given: The rule parameter is provided and valid
      And: The endpointConfiguration type in the RestApi configuration item does not match the endpoint type in rule parameter.
     Then: Return NON_COMPLIANT
  Scenario: 4
    Given: The rule parameter is provided and valid
      And: The endpointConfiguration type in the RestApi configuration item matches the endpoint type in rule parameter.
     Then: Return COMPLIANT
```
