### ISSUE TITLE
New rule on API Gateway stage to check if API GW cache has been enabled and encrypted (API_GW_CACHE_ENABLED_AND_ENCRYPTED).

### ISSUE THREAD

**Issue by Devashish007** [awslabs/aws-config-rules#192]
New rule on API Gateway stage to check if API GW cache has been enabled and encrypted (API_GW_CACHE_ENABLED_AND_ENCRYPTED).

Please provide comments on the gherkin if any.

```
Description:
  Checks whether the API GW stage has cache enabled and is encrypted. The rule is NON_COMPLIANT if the API GW stage is not configured for cache and is not encrypted.

Trigger:
  Configuration Change

Reports on:
  AWS::ApiGateway::Stage

Rule Parameters:
  None

Scenarios:
  Scenario: 1
     Given: The API GW stage caching is not enabled
      Then: Return NON_COMPLIANT
  Scenario: 2
     Given: The API GW stage caching is enabled
       And: The API GW stage caching is not encrypted
      Then: Return NON_COMPLIANT
  Scenario: 3
     Given: The API GW stage caching is enabled
       And: The API GW stage caching is encrypted
      Then: Return COMPLIANT
```
