### ISSUE TITLE
New rule on CLOUDTRAIL_S3_DATAEVENTS_ENABLED to ensure at least one AWS CloudTrail trail logs S3 data events.

### ISSUE THREAD

**Issue by shikharj05** [awslabs/aws-config-rules#195]
Let me know if you have any comments around the Gherkin.
```
Description:
  Checks that at least one AWS CloudTrail trail logs data events for the Amazon S3 service buckets. The rule returns NON_COMPLIANT if none of the trails log data events for Amazon S3 service buckets.
Trigger:
  Periodic
Reports on:
  AWS::::Account
Rule Parameters:
  S3BucketName
   (optional) Comma-separated list of S3 bucket names for which data events logging should be enabled. Default behavior checks for all the buckets.
Scenarios:
  Scenario: 1
    Given: Rule parameter name is invalid
     Then: Return ERROR
  Scenario: 2
    Given: Rule parameter value is invalid
     Then: Return ERROR
  Scenario: 3
    Given: No AWS CloudTrail trail exists
     Then: Return NON_COMPLIANT
  Scenario: 4
    Given: At least one AWS CloudTrail trail exists
      And: None of the trails 'HasCustomEventSelectors' set as 'True'
     Then: Return NON_COMPLIANT
  Scenario: 5
    Given: At least one AWS CloudTrail trail exists
      And: At least one of the trails 'HasCustomEventSelectors' set as 'True'
      And: The Type in 'DataResources' returned from 'get_event_selectors' is not AWS::S3::Object
     Then: Return NON_COMPLIANT
  Scenario: 6
    Given: Rule parameter is provided and valid
      And: At least one AWS CloudTrail trail exists
      And: At least one of the trails 'HasCustomEventSelectors' set as 'True'
      And: The Type in 'DataResources' returned from 'get_event_selectors' is AWS::S3::Object
      And: The Value in 'DataResources' returned from 'get_event_selectors' does not include at least one S3 bucket as specified in rule parameter 'S3BucketName'.
     Then: Return NON_COMPLIANT
  Scenario: 7
    Given: Rule parameter is provided and valid
      And: At least one AWS CloudTrail trail exists
      And: At least one of the trails 'HasCustomEventSelectors' set as 'True'
      And: The Type in 'DataResources' returned from 'get_event_selectors' is AWS::S3::Object
      And: The Value in 'DataResources' returned from 'get_event_selectors' includes the S3 bucket as specified in rule parameter 'S3BucketName'.
     Then: Return COMPLIANT
  Scenario: 8
    Given: Rule parameter value is empty
      And: At least one AWS CloudTrail trail exists
      And: At least one of the trails 'HasCustomEventSelectors' set as 'True'
      And: The Type in 'DataResources' returned from 'get_event_selectors' is AWS::S3::Object
      And: The Value in 'DataResources' returned from 'get_event_selectors' is arn:aws:s3:::
     Then: Return COMPLIANT
```
