### ISSUE TITLE
New rule on SAGEMAKER_NOTEBOOK_INSTANCE_KMS_KEY_CONFIGURED

### ISSUE THREAD

**Issue by kritijha** [awslabs/aws-config-rules#212]
New rule to verify that the Amazon SageMaker Notebook Instance has an AWS KMS key assigned.

Please provide comments on the gherkin if any.

---
```
Description:
  Check whether an AWS KMS key is configured for an Amazon SageMaker Notebook Instance.

Trigger:
  Periodic

Reports on:
  AWS::SageMaker::NotebookInstance

Rule Parameters:
  keyIds 
  (Optional) Comma-separated list of allowed AWS KMS key IDs.

Scenarios:
  Scenario: 1
     Given: The rule parameter 'keyIds' is provided and is invalid
      Then: Return ERROR
  Scenario: 2
     Given: No Amazon SageMaker notebook instances exist
      Then: Return NOT_APPLICABLE
  Scenario: 3
     Given: At least one Amazon SageMaker notebook instance exists
       And: 'KmsKeyId' is not specified for the Amazon SageMaker Notebook Instance
      Then: Return NON_COMPLIANT with annotation "No AWS KMS Key is configured for this Amazon SageMaker Notebook Instance."
  Scenario: 4
     Given: The rule parameter 'keyIds' is provided and is valid
       And: At least one Amazon SageMaker notebook instance exists
       And: 'KmsKeyId' is specified for the Amazon SageMaker Notebook Instance
       And: None of the AWS KMS key IDs specified in the rule parameter 'keyIds' match 'KmsKeyId'
      Then: Return NON_COMPLIANT with annotation "The AWS KMS Key configured for this Amazon SageMaker Notebook Instance is not an KMS Key allowed in the rule parameter (keyIds): <allowed key IDs>."
  Scenario: 5
     Given: The rule parameter 'keyIds' is provided and is valid
       And: At least one Amazon SageMaker notebook instance exists
       And: 'KmsKeyId' is specified in the Amazon SageMaker Notebook Instance
       And: One of the AWS KMS key IDs specified in the rule parameter 'keyIds' matches 'KmsKeyId'
      Then: Return COMPLIANT
  Scenario: 6
     Given: The rule parameter 'keyIds' is not provided
       And: At least one Amazon SageMaker notebook instance exists
       And: 'KmsKeyId' is specified for the Amazon SageMaker Notebook Instance
      Then: Return COMPLIANT
```
