### ISSUE TITLE
New rule on SHIELD_DRT_ACCESS

### ISSUE THREAD

**Issue by schirag1993** [awslabs/aws-config-rules#232]
```
Rule Name:
  SHIELD_DRT_ACCESS

Description:
  Verify that DRT can access the AWS account. As the API Endpoint of this service is only available in us-east-1, this rule should only be scheduled to run in us-east-1 region.

Trigger:
  Periodic

Reports on:
  AWS::::Account

Scenarios:
 Scenario: 1
    Given: AWS Shield Advanced is not enabled
    Then: Return NOT_APPLICABLE
  Scenario: 2
    Given: AWS Shield Advanced is enabled
    And: Role for DRT access is not configured
    Then: Return NON_COMPLIANT with annotation "DRT team does not have access to account."
  Scenario: 3
    Given: AWS Shield Advanced is enabled
    And: Role for DRT access is configured
    Then: Return COMPLIANT
```
