### ISSUE TITLE
New rule on CLOUDWATCH_LOG_GROUP_ENCRYPTED

### ISSUE THREAD

**Issue by rafihm** [awslabs/aws-config-rules#233]
```
"""
#####################################
##           Gherkin               ##
#####################################
Rule Name:
    CLOUDWATCH_LOG_GROUP_ENCRYPTED

Description:
    Checks whether the AWS CloudWatch Log Group is encrypted. The rule is NON_COMPLIANT if the CloudWatch has Log Group without encryption enabled.

Trigger:
    Periodic

Reports on:
    AWS::Logs::LogGroup

Rule Parameters:
  KmsKeyId (Optional)
    ARN of the KMS key that is used to encrypt the CloudWatch Log Group

Scenarios:
  Scenario: 1
    Given: The rule parameters KmsKeyId has invalid ARN Value.
    Then: return ERROR

  Scenario: 2
    Given: No CloudWatch Log Group is present.
    Then: Return NOT_APPLICABLE

  Scenario: 3
    Given: At least one CloudWatch Log Group is present.
    And: Log Group is not encrypted (DescribeLogGroups call does not return the 'kmsKeyId' name/value pair).
    Then: Return NON_COMPLIANT

  Scenario: 4
    Given: At least one CloudWatch Log Group is present.
    And: Log Group is encrypted (DescribeLogGroups call does not return the 'kmsKeyId' name/value pair).
    And: KmsKeyId parameter is not configured.
    Then: Return COMPLIANT

  Scenario: 5
    Given: At least one CloudWatch Log Group is present.
    And: Log Group is encrypted (DescribeLogGroups call returns the 'kmsKeyId' name/value pair).
    And: KmsKeyId parameter is configured.
    And: KmsKeyId parameter is not matching the KmsKeyId value from the DescribeLogGroups API call.
    Then: Return NON_COMPLIANT

  Scenario: 6
    Given: At least one CloudWatch Log Group is present.
    And: Log Group is encrypted (DescribeLogGroups call returns the 'kmsKeyId' name/value pair).
    And: KmsKeyId parameter is configured.
    And: KmsKeyId parameter is matching the KmsKeyId value from the DescribeLogGroups API call.
    Then: Return COMPLIANT
"""
```

The rule is periodic and we need to use the API call [DescribeLogGroups](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogGroups.html) to get the logs group list along with the details (Max 50 log groups in single call). 
If the the log group is encrypted then it returns `kmsKeyId` name/value pair. 
example:
```
$ aws logs describe-log-groups --log-group-name /aws/lambda/test
{
    "logGroups": [
        {
            "storedBytes": 0, 
            "metricFilterCount": 0, 
            "creationTime": 1543925259496, 
            "logGroupName": "/aws/lambda/test", 
            "kmsKeyId": "arn:aws:kms:us-west-2:123456789012:key/47ef70c0-0000-000000000-2d7000007b57", 
            "arn": "arn:aws:logs:us-west-2:123456789012:log-group:/aws/lambda/test:*"
        }
    ]
}
```
